services:
#  weting_nginx:
#    container_name: weting_nginx
#    image: nginx:stable-alpine
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/templates:/etc/nginx/templates
#    ports:
#      - "80:80"
#    depends_on:
#      - weting_server
#    networks:
#      - weting-network
  weting_server:
    container_name: weting-server
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./src/configs/.env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run start:dev
    ports:
      - "4000:4000"
    depends_on:
      - weting_db
    networks:
      - weting-network

  weting_db:
    container_name: weting_db
    image: postgres:15
    env_file:
      - ./src/configs/.env.development
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - weting-network

networks:
  weting-network:
    driver: bridge